# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deppv', models.TextField()),
                ('depmd', models.CharField(max_length=200)),
                ('depbc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.TextField()),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.TextField()),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.TextField()),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.FileField(upload_to=b'')),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='md',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.TextField()),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mindec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.TextField()),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.TextField()),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='unsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele1', models.TextField()),
                ('tele2', models.CharField(max_length=200)),
                ('tele3', models.TextField()),
                ('mail1', models.TextField()),
                ('mail2', models.TextField()),
                ('mail3', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
