# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-13 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='center_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='homepage',
        ),
        migrations.RenameField(
            model_name='adr',
            old_name='depmd',
            new_name='depname',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='address',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='tele2',
            new_name='contact_type',
        ),
        migrations.RemoveField(
            model_name='adr',
            name='depbc',
        ),
        migrations.RemoveField(
            model_name='adr',
            name='deppv',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='mail1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='mail2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='mail3',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='tele1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='tele3',
        ),
        migrations.AddField(
            model_name='adr',
            name='adrfile',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
