# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-13 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170513_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center_news',
            old_name='Photo',
            new_name='photo',
        ),
    ]
