# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170513_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='center_news',
            new_name='Centernews',
        ),
    ]
