# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20170514_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centernews',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
