# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20170514_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centernews',
            name='title',
        ),
        migrations.AddField(
            model_name='centernews',
            name='readmore',
            field=models.TextField(null=True),
        ),
    ]
