# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170514_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centernews',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
