# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20170516_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddl',
            name='ddl',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='pvnewsletters',
            name='newsletter',
            field=models.FileField(upload_to=b''),
        ),
    ]
