# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20170520_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoname', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
