# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-21 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_pvnewsletters_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmp',
            old_name='rmp',
            new_name='paragraph',
        ),
    ]
