# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('title1', models.TextField(max_length=200, null=True)),
                ('title2', models.TextField(max_length=200, null=True)),
                ('title3', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='legislation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, null=True)),
                ('link1', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link2', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link3', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link4', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link5', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link6', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link7', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link8', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link9', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link10', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link11', models.FileField(blank=True, null=True, upload_to=b'')),
                ('link12', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.RenameField(
            model_name='adr',
            old_name='adrfile',
            new_name='file1',
        ),
        migrations.RemoveField(
            model_name='adr',
            name='depname',
        ),
        migrations.RemoveField(
            model_name='psur',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='psur',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='rmp',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='rmp',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='adr',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='adr',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='adr',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='adr',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='adr',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='psur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='psur',
            name='title1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psur',
            name='title2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psur',
            name='title3',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pvddl',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='pvnewsletters',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='rmp',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='rmp',
            name='title1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rmp',
            name='title2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rmp',
            name='title3',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pvddl',
            name='pvddl',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
