# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20170523_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvddl',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pvddl',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
