# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20170523_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvddl',
            name='month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pvddl',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
