# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20170523_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regionalcenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph1', models.TextField(blank=True, max_length=200, null=True)),
                ('paragraph2', models.TextField(blank=True, max_length=200, null=True)),
                ('paragraph3', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='pv',
        ),
        migrations.RemoveField(
            model_name='guideline',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='guideline',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='guideline',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='legislation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='psur',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='psur',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='psur',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='rmp',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='rmp',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='rmp',
            name='title3',
        ),
        migrations.AddField(
            model_name='guideline',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guideline',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guideline',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legislation',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legislation',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='legislation',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psur',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psur',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psur',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rmp',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rmp',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rmp',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pvnewsletters',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pvnewsletters',
            name='month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pvnewsletters',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
