# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_auto_20170523_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('psur', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('rmp', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('pvnewsletter', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('legisation', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('pvddl', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='guideline',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='psur',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pvddl',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pvnewsletters',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='rmp',
            name='photo',
        ),
    ]
