# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_auto_20170523_0605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Images',
        ),
    ]
